{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-migration.fullname" . }}-db
  labels:
    {{- include "keycloak-migration.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  DB_ADMIN_PASSWORD: {{ .Values.database.password | b64enc | quote }}
{{- end }}
